### ISSUE TITLE
cannot load such file -- easy_globalize3_accessors (LoadError)

### ISSUE THREAD

**Issue by olivierbuffon** [jipiboily/spree_multi_lingual#11]
Hi, 
I trying to deploy your extension on a spree store v1.1 but when I'm running the rails g spree_multi_lingual:install command I obtain this error :

/Users/olivierbuffon/.rvm/gems/ruby-1.9.3-p125/gems/polyglot-0.3.3/lib/polyglot.rb:63:in `require': cannot load such file -- easy_globalize3_accessors (LoadError)

Do you have any idea to solve that problem ?

Thanks.

**Comment by olivierbuffon** [comment]
I tried to change my version of ruby, to change the version of polyglot ... same error ...
Here, my Gemfile content:

Using rake (0.9.2.2) 
Using i18n (0.6.0) 
Using multi_json (1.3.6) 
Using activesupport (3.2.3) 
Using builder (3.0.0) 
Using activemodel (3.2.3) 
Using erubis (2.7.0) 
Using journey (1.0.3) 
Using rack (1.4.1) 
Using rack-cache (1.2) 
Using rack-test (0.6.1) 
Using hike (1.2.1) 
Using tilt (1.3.3) 
Using sprockets (2.1.3) 
Using actionpack (3.2.3) 
Using mime-types (1.18) 
Using polyglot (0.3.3) 
Using treetop (1.4.10) 
Using mail (2.4.4) 
Using actionmailer (3.2.3) 
Using active_utils (1.0.3) 
Using braintree (2.16.0) 
Using json (1.7.3) 
Using money (3.7.1) 
Using activemerchant (1.20.4) 
Using arel (3.0.2) 
Using tzinfo (0.3.33) 
Using activerecord (3.2.3) 
Using activeresource (3.2.3) 
Using acts_as_list (0.1.4) 
Using gyoku (0.4.5) 
Using akami (1.0.0) 
Using multi_xml (0.5.1) 
Using httparty (0.8.3) 
Using nokogiri (1.5.3) 
Using uuidtools (2.1.2) 
Using aws-sdk (1.3.9) 
Using bcrypt-ruby (3.0.1) 
Using bundler (1.2.0.pre) 
Using cancan (1.6.7) 
Using cocaine (0.2.1) 
Using coffee-script-source (1.3.3) 
Using execjs (1.4.0) 
Using coffee-script (2.2.0) 
Using rack-ssl (1.3.2) 
Using rdoc (3.12) 
Using thor (0.14.6) 
Using railties (3.2.3) 
Using coffee-rails (3.2.2) 
Using rails (3.2.3) 
Using deface (0.9.1) 
Using orm_adapter (0.0.7) 
Using warden (1.1.1) 
Using devise (2.0.4) 
Using paper_trail (2.6.3) 
Using globalize3 (0.2.0) 
Using easy_globalize3_accessors (1.2.0) 
Using ffaker (1.12.1) 
Using highline (1.6.11) 
Using httpi (0.9.7) 
Using jquery-rails (2.0.2) 
Using kaminari (0.13.0) 
Using nested_set (1.7.0) 
Using nori (1.1.0) 
Using paperclip (2.7.0) 
Using polyamorous (0.5.0) 
Using rabl (0.6.5) 
Using rack-contrib (1.1.0) 
Using ransack (0.6.0) 
Using routing-filter (0.3.1) 
Using sass (3.1.19) 
Using sass-rails (3.2.5) 
Using wasabi (2.1.1) 
Using savon (0.9.9) 
Using state_machine (1.1.2) 
Using stringex (1.3.3) 
Using spree_core (1.1.1) 
Using spree_auth (1.1.1) 
Using spree_api (1.1.1) 
Using spree_cmd (1.1.1) 
Using spree_dash (1.1.1) 
Using spree_promo (1.1.1) 
Using spree_sample (1.1.1) 
Using spree (1.1.1) 
Using spree_multi_lingual (0.1.0.alpha1) from git@github.com:jipiboily/spree_multi_lingual.git (at master) 
Using spree_skrill (1.0.2) 
Using spree_usa_epay (1.0.2) 
Using sqlite3 (1.3.6) 
Using uglifier (1.2.4) 

Really strange ... :(

**Comment by olivierbuffon** [comment]
I fixed it !
It's not a real fix but ... it works for me, so... I hope it help someone else !

So, apparently there is a problem with rails 3.2.3 and easy_globalize3_accessors gem ...
I removed (temporarily) the gem from the gemspec file and then I've just add this gem to my application Gemfile :
gem 'easy_globalize3_accessors', :git => "git://github.com/reinkcar/easy_globalize3_accessors.git"

By the way, globalize3 gem is now in 0.2.0 stable, so I suggest you to update that in your gem spec file :)

So now everything is working fine !
I hope this could help ;)

**Comment by jipiboily** [comment]
Thanks for the comment! It sure might help people in the future.
