### ISSUE TITLE
price in edit product rendered with separator but saved stripped

### ISSUE THREAD

**Issue by matteofuzz** [jipiboily/spree_multi_lingual#12]
Spree 1.1.1, spree_multi_lingual 1-1-stable branch.
I set :it as default on spree configuration and ['it', 'en'] in spree_multi_lingual initalizer.
In edit product field price is localized in :en, as 1,111.11 with separator and when I save it became 1.11 
Same result with 1.111,11 (localization in italian).
Only work without separator, 1111.11 is saved correctly, as 1111,11 .
I try add delocalize gem without results.

**Comment by sbounmy** [comment]
hi @matteofuzz,
I am sorry I don't much about the currency separators. maybe you could ping @radar, he is the one who knows best!
