### ISSUE TITLE
translations strips return line and tabs

### ISSUE THREAD

**Issue by sbounmy** [jipiboily/spree_multi_lingual#13]
hi @jipiboily,

are here any reason we are stripping out return line and tabs ? 

https://github.com/jipiboily/spree_multi_lingual/blob/master/app/views/spree/admin/shared/_language_dropdown.html.erb#L14

This might be an issue when translating textarea like I am doing with spree_essential_cms : https://github.com/sbounmy/spree_essential_cms/tree/i18n

**Comment by jipiboily** [comment]
Nope, doesn't see why at first. Maybe to prevent multi-line variable assignment, but javascript escaping should prevent that, so no, no good reason to do that.

**Comment by sbounmy** [comment]
@jipiboily thanks ! I removed that https://github.com/jipiboily/spree_multi_lingual/commit/6eb056e10f4678901bffa37496b37134832a0d8a
If anyone is experiencing regression, we will reopen this issue.

**Comment by jipiboily** [comment]
Thanks for the work @sbounmy, really appreciated by me, and certainly a bunch of ppl! :)

**Comment by sbounmy** [comment]
thanks for the kind words @jipiboily :) I believe we can get a gem release soon :beer: !
I hope that people will keep maintaining and create new spree extensions because there are still a lot more to do :)
