### ISSUE TITLE
Something wrong in README.md

### ISSUE THREAD

**Issue by n5ken** [jipiboily/spree_multi_lingual#16]
In the installation part, I can't bundle the gem with adding the following code to Gemfile

```
gem "spree_multi_lingual", :git => "git@github.com:jipiboily/spree_multi_lingual.git"
```

And it should be

```
gem 'spree_multi_lingual', :git => 'git://github.com/jipiboily/spree_multi_lingual.git'
```

**Comment by n5ken** [comment]
Additional issue, the I18n in the code below should have I lower case

```
# config/application.rb
config.I18n.fallbacks = true
```

like this

```
# config/application.rb
config.i18n.fallbacks = true
```

otherwise

```
rake aborted!
undefined method `I18n' for #<Rails::Application::Configuration:0x00000001b125f0>
```

**Comment by Davidslv** [comment]
Seems the owner isn't available for a while, I corrected that and also add Option Values to be translated.

**Comment by jipiboily** [comment]
I will take a look at that "soon".

@Davidslv is your work on your fork or something that could be pulled here?

(sorry for the delay, I was in vacations)

**Comment by jipiboily** [comment]
Oh, sorry, there is a PR for that...

**Comment by Davidslv** [comment]
Hi, yes, I think you have all the necessary code in my pull request. In a newer version I also added support for pages (using the gem spree_pages), but I don't think that could be relevant once is not part of the spree core.

**Comment by jipiboily** [comment]
To have pages managed via Monologue UI? It seems to be an equivalent to spree_static_content, right?

**Comment by sbounmy** [comment]
readme fixed. thanks and sorry for the delay
