### ISSUE TITLE
Unable to change the locale in products

### ISSUE THREAD

**Issue by n5ken** [jipiboily/spree_multi_lingual#17]
I am not able to change the locale to update as the SWF video in Readme.md, I am using Chrome, and when I am selecting the locale in product edit page, nothing happen, is it under construction right now?

**Comment by jipiboily** [comment]
It should work. Can you take a look at your javascript console and paste it's content in a gist or here?

Also, what version of Spree are you using and what branch of spree_multi_lingual are you using?
