### ISSUE TITLE
multi currency with multi lingual

### ISSUE THREAD

**Issue by umuthan** [jipiboily/spree_multi_lingual#22]
i want to add different price for each language.
it can not possible with multi lingual now but can you attach this funtionality?

**Comment by jipiboily** [comment]
Hum, this would probably need quite a bit of work. I personnaly don't have time to do that. Sorry.

Will let that open if someone want to do it!

(sorry for the delay, I was in vacations)

**Comment by sbounmy** [comment]
we don't have plan for this feature yet, but pull requests are welcome ;)
