### ISSUE TITLE
Support for spree version 1.2

### ISSUE THREAD

**Issue by spaudanjo** [jipiboily/spree_multi_lingual#28]

**Comment by spaudanjo** [comment]
Are there any plans for the near future for supporting spree version 1.2?

**Comment by jipiboily** [comment]
I am not maintaing this project myself anymore. @sbounmy and @bricesanchez are maintaining it.

All that said, it seems there is now a "1.2" branch: https://github.com/jipiboily/spree_multi_lingual/tree/1.2

As a side note: nothing official, but I think Spree team is looking at integrating this kind of feature for Spree 2.0. If this happens to turn into reality, they most probably won't use this extension but code something straight into the core from scratch, which is a great idea.

**Comment by spaudanjo** [comment]
Thanks for the hint :-)

**Comment by sbounmy** [comment]
@spaudanjo spree 1.2 supported in branch 1.2 https://github.com/jipiboily/spree_multi_lingual/tree/1.2 :)
