### ISSUE TITLE
Heroku Issue

### ISSUE THREAD

**Issue by sibanand-cis** [jipiboily/spree_multi_lingual#31]
fatal: The remote end hung up unexpectedly
       Git error: command `git clone 'git@github.com:jipiboily/spree_multi_lingual.git' "/tmp/build_3syaahufqs1y8/vendor/bundle/ruby/1.9.1/cache/bundler/git/spree_multi_lingual-f89b8dade805d6961a231a32f085ca3c907e0ce1" --bare --no-hardlinks` in directory /tmp/build_3syaahufqs1y8 has failed.
 !
 !     Failed to install gems via Bundler.
 !
 !     Heroku push rejected, failed to compile Ruby/rails app

To git@heroku.com:frozen-cliffs-7645.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'git@heroku.com:frozen-cliffs-7645.git'

**Comment by sibanand-cis** [comment]
LAter I found out the solution at:http://stackoverflow.com/questions/13362288/heroku-push-rejected-submodule-install-failed.

My repo suddenly stopped pushing, and these two things 'fixed' it:

Change all public submodule URLs (if any) from using the ssh transport URLs to readonly git transport URLs (i.e., from git@github.com:yaniv-aknin/public-project to git://github.com/yaniv-aknin/public-project). To do this, you will need to edit the file called .gitmodules in the root of your repo.
Remove all private submodules (if any) from my repo (remove them from .gitmodules and rm -fr their directories).
Commit the changes.

**Comment by sbounmy** [comment]
this seems not related to spree_multi_lingual, but thanks for reporting :) !
