### ISSUE TITLE
don't know if it's a bug or misuse ...

### ISSUE THREAD

**Issue by ghost** [jipiboily/spree_multi_lingual#41]
I installed and used your gem wo any trouble until then ... ( w spree-example demo)
Now I started translating (setting up)  the products descriptions into :en and :fr 
Got correctly in spree_product_translations 2 records for the same spree_product_id one for each locale...  ( 16 rows in spree_products , 32 rows in spree_product_translations..)

When displaying the products on the home page (  previously 6 items per page., 3 pages ).. 
now the pagination changed ,  I have the double of pages 6 pages ! and added 3 are empty ...  so it's a matter of pagination ...  any clue ?

thanks

**Comment by sbounmy** [comment]
I find out an issue with product which have no translations.
I've fixed it with a better approach : https://github.com/jipiboily/spree_multi_lingual/commit/70f0a62de2cc726309005ba6e21b737bc6a40928
can you pull master and give it a try ?

**Comment by ghost** [comment]
crash  see console log   Syntax error in a Deface ...

=>    https://gist.github.com/erwin/5296246

using gemfile : 

source 'https://rubygems.org'
gem 'rails', '3.2.13'
gem 'mysql2'
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
en
gem 'jquery-rails'
group :development do
    gem 'debugger'
    gem 'thin'
    gem 'yaml_db'
end
gem 'spree',  :github => 'spree/spree' , :branch => '1-3-stable'
gem 'spree_gateway', :github => 'spree/spree_gateway', :branch => '1-3-stable'
gem 'spree_auth_devise', :github => 'spree/spree_auth_devise', :branch => '1-3-stable'

gem 'spree_i18n', :github => 'spree/spree_i18n'
gem 'spree_multi_lingual', git: "git@github.com:jipiboily/spree_multi_lingual.git"

gem 'spree_static_content', :github => 'spree/spree_static_content', :branch => '1-3-stable'
gem 'spree_editor', :github => 'spree/spree_editor', :branch => '1-3-stable'
gem 'tinymce-rails', '>= 3.4.7.0.1'
gem 'spree_paypal_express', :github => 'spree/spree_paypal_express', :branch => '1-3-stable'

**Comment by ghost** [comment]
issue seems to be located in   the comment line : overrides/spree/admin/taxons/_forms/replace_permalink_part_by_permalink.html.erb.deface

```
<!-- replace "code[erb-loud]:contains('f.field_container :permalink_part do')" closing_selector 'code[erb-silent]:contains("end")' enabled -->

<%= f.field_container :permalink do %>
  <%= f.label :permalink, t(:permalink) %><span class="required">*</span><br />
  <%= @taxon.permalink.split("/")[0...-1].join("/") + "/" %><%= text_field_tag "taxon[permalink]", @permalink_part %>
<% end %>
```

**Comment by sbounmy** [comment]
Its working for me on spree 1.3.2 and I've tried 1-3-stable aswell.
Anyway I've refactored the override, please let me know if it works.
Do you have any customization ? Or try to use latest deface : 

``` ruby
gem 'deface', '1.0.0.rc1'
```

**Comment by ghost** [comment]
working for me now too...   added globalize and  deface gems just in case .. (not sure it's necessary)

gem 'deface', '1.0.0.rc1'
gem 'globalize3'
gem 'spree',  :github => 'spree/spree' , :branch => '1-3-stable'
..
gem 'spree_i18n', :github => 'spree/spree_i18n'
gem 'spree_multi_lingual', git: "git@github.com:jipiboily/spree_multi_lingual.git"

in staging phase now, weill keep you informed  ( need to be  :en and :fr  in production )
