### ISSUE TITLE
spree_shipping_categories

### ISSUE THREAD

**Issue by ghost** [jipiboily/spree_multi_lingual#42]
Any reason why there is no spree_shipping_categories  translation ?
used in admin... but as other contents are translated ... the method name could be too 
In this case the value is correctly translated but not the property label ...

![Capture d e cran 2013-04-05 a 16 44 45](https://f.cloud.github.com/assets/11973/344422/cd0d504e-9dff-11e2-8e6c-0d0868b12534.png)

**Comment by sbounmy** [comment]
no particular reason but feel free to do a pull request for that :)
