### ISSUE TITLE
syntax error from deface during installation

### ISSUE THREAD

**Issue by danidrops** [jipiboily/spree_multi_lingual#43]
I followed the readme instructions (with gem 'globalize3', '0.2.0' in gemfile to get around dependency)
until...

 rails g spree_multi_lingual:install
    [...]/deface-0.9.1/lib/deface/dsl/loader.rb:28:in `instance_eval': (eval):1: syntax error, unexpected tIDENTIFIER, expecting $end (SyntaxError)
    ...ink_part do')" closing_selector 'code[erb-silent]:contains("...
    ...                               ^
    from [...]/deface-0.9.1/lib/deface/dsl/loader.rb:28:in`block in load'
    from [...]/deface-0.9.1/lib/deface/dsl/loader.rb:17:in `open'
    from [...]/deface-0.9.1/lib/deface/dsl/loader.rb:17:in`load'
    from [...]/deface-0.9.1/lib/deface/environment.rb:66:in `block (2 levels) in enumerate_and_load'
    from [...]/deface-0.9.1/lib/deface/environment.rb:65:in`glob'
    from [...]/deface-0.9.1/lib/deface/environment.rb:65:in `block in enumerate_and_load'
    from [...]/deface-0.9.1/lib/deface/environment.rb:55:in`each'
    from [...]/deface-0.9.1/lib/deface/environment.rb:55:in `enumerate_and_load'
    from [...]/deface-0.9.1/lib/deface/environment.rb:49:in`load_overrides'
    from [...]/deface-0.9.1/lib/deface/environment.rb:31:in `block in load_all'
    from [...]/deface-0.9.1/lib/deface/environment.rb:29:in`each'
    from [...]/deface-0.9.1/lib/deface/environment.rb:29:in `load_all'
    from [...]/deface-0.9.1/lib/deface/railtie.rb:12:in`activate'
    from [...]/activesupport-3.2.12/lib/active_support/callbacks.rb:429:in `_run__3500165977034887579__prepare__3119406908442186579__callbacks'
    from [...]/activesupport-3.2.12/lib/active_support/callbacks.rb:405:in`__run_callback'
    from [...]/activesupport-3.2.12/lib/active_support/callbacks.rb:385:in `_run_prepare_callbacks'
    from [...]/activesupport-3.2.12/lib/active_support/callbacks.rb:81:in`run_callbacks'
    from [...]/actionpack-3.2.12/lib/action_dispatch/middleware/reloader.rb:74:in `prepare!'
    from [...]/actionpack-3.2.12/lib/action_dispatch/middleware/reloader.rb:48:in`prepare!'
    from [...]/railties-3.2.12/lib/rails/application/finisher.rb:47:in `block in <module:Finisher>'
    from [...]/railties-3.2.12/lib/rails/initializable.rb:30:in`instance_exec'
    from [...]/railties-3.2.12/lib/rails/initializable.rb:30:in `run'
    from [...]/railties-3.2.12/lib/rails/initializable.rb:55:in`block in run_initializers'
    from [...]/railties-3.2.12/lib/rails/initializable.rb:54:in `each'
    from [...]/railties-3.2.12/lib/rails/initializable.rb:54:in`run_initializers'
    from [...]/railties-3.2.12/lib/rails/application.rb:136:in `initialize!'
    from [...]/railties-3.2.12/lib/rails/railtie/configurable.rb:30:in`method_missing'
    from /Users/daniellebakhazi/Sites/rudy/config/environment.rb:5:in `<top (required)>'
    from [...]/polyglot-0.3.3/lib/polyglot.rb:63:in`require'
    from [...]/polyglot-0.3.3/lib/polyglot.rb:63:in `require'
    from [...]/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in`block in require'
    from [...]/activesupport-3.2.12/lib/active_support/dependencies.rb:236:in `load_dependency'
    from [...]/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in`require'
    from [...]/railties-3.2.12/lib/rails/application.rb:103:in `require_environment!'
    from [...]/railties-3.2.12/lib/rails/commands.rb:25:in`<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in`<main>'

I'm running ruby-1.9.3-p286 (via RVM) and Rails 3.2.12. 

Any ideas? I saw that @sbounmy posted a similar [issue](https://github.com/spree/spree_fancy/issues/5) about this, but there is no fix as far as I can see.

**Comment by ghost** [comment]
Hi i had the same problem, in my case i had old version of deface gem.
Try bundle show deface, the right version is  '1.0.0.rc2'

**Comment by danidrops** [comment]
That's just it! Thank you :)

to update...
gem 'deface', :git => 'git://github.com/spree/deface.git'
(it has moved homes)

**Comment by sbounmy** [comment]
yes we have issue with deface since 1.0.0rc4 : https://github.com/jipiboily/spree_multi_lingual/issues/47
Here is the deface issue : https://github.com/spree/deface/issues/113
