### ISSUE TITLE
I18n.locale = order.locale, NoMethodError (undefined method `locale' for 33:Fixnum)

### ISSUE THREAD

**Issue by picazoH** [jipiboily/spree_multi_lingual#44]
Switch the mailers to be invoked using ids, not model objects.

I think is related to this change: https://github.com/spree/spree/commit/20b5ba145bb777d38afdb25b78781c940c2b0002

**Comment by sbounmy** [comment]
This have been fixed here: https://github.com/jipiboily/spree_multi_lingual/commit/a9eef2bca72fa7391b079d57cce5ea34a831b5c7
sorry for the late answer
