### ISSUE TITLE
description in ShippingMethod decorator

### ISSUE THREAD

**Issue by picazoH** [jipiboily/spree_multi_lingual#48]
I think you should add description to shipping_method_decorator according to migration add_description_to_shipping_method.spree_multi_lingual

module Spree
  ShippingMethod.class_eval do
    translates :name, :description
  end
end

**Comment by sbounmy** [comment]
Thanks for reporting ! fixed in master and 2-0-stable

**Comment by picazoH** [comment]
could you please fix de 1-3-stable? Thank you.

**Comment by sbounmy** [comment]
here we go x)
