### ISSUE TITLE
root_path vs request.fullpath issues

### ISSUE THREAD

**Issue by fbernier** [jipiboily/spree_multi_lingual#6]
I am having an issue with i18n and spree. If you look this file:

https://github.com/spree/spree/blob/1-1-stable/core/app/helpers/spree/admin/navigation_helper.rb

If you look line 27, I'm having a particular issue where request.fullpath returns does not return the locale at the beginning of the path, while root_path is '/:locale', in my case '/:fr'. So the string comparison made at this line is never met.

I could not think of a proper fix for this particular case. Anyone got a clue?

**Comment by sbounmy** [comment]
hi @fbernier,

Looks like this happens with spree 1.1, I am not sure how to fix this yet.
I am still using spree_multi_lingual with spree 1.0 but I will migrate soon to spree 1.1 and fix this asap.

**Comment by sbounmy** [comment]
hi @fbernier,

I ran into the similar issue with spree 1.1.
The issue comes from routing-filter, which is fixed on master : https://github.com/svenfuchs/routing-filter/issues/7

Adding this to my gemfile fixed it for me:

``` ruby
gem 'routing-filter', :git => 'git://github.com/svenfuchs/routing-filter.git'
```

**Comment by sbounmy** [comment]
I am closing this. If this issue occurs again, I will reopen! thanks
