### ISSUE TITLE
Can't mass-assign protected attributes

### ISSUE THREAD

**Issue by vagels** [jipiboily/spree_multi_lingual#7]
I got  message "Can't mass-assign protected attributes: locale" when doing the migration.

**Comment by sbounmy** [comment]
can you specify which version of spree and spree_multi_lingual you are using ?

**Comment by vagels** [comment]
Using spree (1.1.1) 
Using spree_multi_lingual (0.1.0.alpha1) from git://github.com/sbounmy/spree_multi_lingual.git (at master)

**Comment by vagels** [comment]
After clean install (wo data) in migrations all is ok, but

ActiveModel::MassAssignmentSecurity::Error in Spree/home#index

Showing .../gems/spree_core-1.1.1/app/views/spree/shared/_taxonomies.html.erb where line #3 raised:

Can't mass-assign protected attributes: locale

**Comment by sbounmy** [comment]
my fork is no longer maintained.
This repo with the branch 1-0-stable is the last up-to-date. You can maybe try to update the dependencies to spree 1.1 and give it a try.

I will asap provide a spree 1.1 support

**Comment by jipiboily** [comment]
the @sbounmy fork was specified in README, just fixed that. That said, this is probably an issue.

@vagels: are you using latest Rails (3.2.3)? With `config.active_record.whitelist_attributes` set to `true`, right?

**Comment by vagels** [comment]
yes 3.2.3 and true

**Comment by sbounmy** [comment]
@vagels I just pushed a 1-1-stable branch, can you please give it a try ?
@jipiboily would be great to have this repo running on travis, can you link it with your account ?

**Comment by sbounmy** [comment]
@jipiboily nevermind, it is already setup. It's late I think I need some sleep!

**Comment by sbounmy** [comment]
@vagels looks like the issue remains, locale is still protected.
https://github.com/svenfuchs/globalize3/issues/128 is a temporary fix, I will looking into this tomorrow.

**Comment by sbounmy** [comment]
@vagels I did the quick fix, you can try now :)

**Comment by sbounmy** [comment]
I am closing this, if this occurs again we will reopen. thanks!
