### ISSUE TITLE
Migration error on 1-1-stable

### ISSUE THREAD

**Issue by matteofuzz** [jipiboily/spree_multi_lingual#8]
I have an error running migrations on 1-1-stable branch:

```
** Execute db:migrate
==  MigrateDataForProducts: migrating =========================================
rake aborted!
An error has occurred, all later migrations canceled:

Can't mass-assign protected attributes: id, created_at, updated_at, count_on_hand
```

Then I temporary add this line

``` ruby
attr_accessible :id, :created_at, :updated_at, :count_on_hand
```

 to Spree::Product model and they run smooth.

I don't know how o solve this issue without override the model.

**Comment by sbounmy** [comment]
changing the migration to

``` ruby
product.update_attributes!(product.untranslated_attributes, :without_protection => true)
```

would fix it.
I will patch this migration for ppl who are running on fresh spree 1.1 installs

**Comment by matteofuzz** [comment]
I confirm that with the patch migration run without problems (tested on deployment).
